### ISSUE TITLE
BannerStyle adaptive has no button padding

### ISSUE THREAD

**Issue by sawirricardo** [TesteurManiak/smart_banner#1]
Hi, thanks for the package. Is there a way to customize the button?

**Comment by TesteurManiak** [comment]
Hi, could you be more explicit please. What are you trying to do ? What is blocking you in the package API ?

**Comment by sawirricardo** [comment]
I tested the web running on macos, and the button styling is off since it's a macOS (different from iOS). That's not handled yet.

**Comment by TesteurManiak** [comment]
Yeah currently the package only implement the specs for Android and iOS. I'm not sure how the banner should be designed with a desktop view 🤔

**Comment by sawirricardo** [comment]
Probably add detection for .macOS, should just use the iOS?

Ive done this through in userland

**Comment by TesteurManiak** [comment]
Sorry for the wait @sawirricardo, I've published a fix on the repo to detect when the browser is running on the MacOS platform and display the iOS style banner.
I'll publish an update of the package as soon as I can.
