### ISSUE TITLE
How to keep the SmartBanner on every route until closed?

### ISSUE THREAD

**Issue by aytunch** [TesteurManiak/smart_banner#3]
Hi @TesteurManiak thanks for this easy to use package.
Once we wrap our `MaterialApp`'s child with `SmartBannerScaffold`, we see the banner on our initial route.
But when we push named routes, or modal pages, or other scaffolds, the banner disappears.
Am I doing something wrong?
I want the banner to be seen in my mobile web app until the user presses the close button.

**Comment by TesteurManiak** [comment]
Hi @aytunch if you try the online example (https://rouxguillau.me/smart_banner/#/), you can see that pushing a page doesn't dismiss the banner, it might have something to do with your implementation. Is your code similar to the example ? https://github.com/TesteurManiak/smart_banner/blob/main/example/lib/main.dart#L47

**Comment by aytunch** [comment]
Thanks for pointing me to the right direction. Now it works fine. Problem was on my code.
